from .cont_cc_sixpmsm_env import ContCurrentControlSixPhasePermanentMagnetSynchronousMotorEnv
from .cont_sc_sixpmsm_env import ContSpeedControlSixPhasePermanentMagnetSynchronousMotorEnv
from .cont_tc_sixpmsm_env import ContTorqueControlSixPhasePermanentMagnetSynchronousMotorEnv
from .finite_cc_sixpmsm_env import FiniteCurrentControlSixPhasePermanentMagnetSynchronousMotorEnv
from .finite_sc_sixpmsm_env import FiniteSpeedControlSixPhasePermanentMagnetSynchronousMotorEnv
from .finite_tc_sixpmsm_env import FiniteTorqueControlSixPhasePermanentMagnetSynchronousMotorEnv