from .cont_sc_synrm_env import ContSpeedControlSynchronousReluctanceMotorEnv
from .cont_tc_synrm_env import ContTorqueControlSynchronousReluctanceMotorEnv
from .cont_cc_synrm_env import ContCurrentControlSynchronousReluctanceMotorEnv
from .finite_tc_synrm_env import FiniteTorqueControlSynchronousReluctanceMotorEnv
from .finite_sc_synrm_env import FiniteSpeedControlSynchronousReluctanceMotorEnv
from .finite_cc_synrm_env import FiniteCurrentControlSynchronousReluctanceMotorEnv
