from .cont_sc_pmsm_env import ContSpeedControlPermanentMagnetSynchronousMotorEnv
from .cont_tc_pmsm_env import ContTorqueControlPermanentMagnetSynchronousMotorEnv
from .cont_cc_pmsm_env import ContCurrentControlPermanentMagnetSynchronousMotorEnv
from .finite_tc_pmsm_env import FiniteTorqueControlPermanentMagnetSynchronousMotorEnv
from .finite_sc_pmsm_env import FiniteSpeedControlPermanentMagnetSynchronousMotorEnv
from .finite_cc_pmsm_env import FiniteCurrentControlPermanentMagnetSynchronousMotorEnv
