from .squirrel_cage_induc_motor_env import ContSquirrelCageInductionMotorEnvironment
from .squirrel_cage_induc_motor_env import DiscSquirrelCageInductionMotorEnvironment
from .doubly_fed_induc_motor_env import ContDoublyFedInductionMotorEnvironment
from .doubly_fed_induc_motor_env import DiscDoublyFedInductionMotorEnvironment

from .squirrel_cage_induction_motor_envs import DqContCurrentControlSquirrelCageInductionMotorEnv
from .squirrel_cage_induction_motor_envs import DqContSpeedControlSquirrelCageInductionMotorEnv
from .squirrel_cage_induction_motor_envs import DqContTorqueControlSquirrelCageInductionMotorEnv
from .squirrel_cage_induction_motor_envs import AbcContCurrentControlSquirrelCageInductionMotorEnv
from .squirrel_cage_induction_motor_envs import AbcContSpeedControlSquirrelCageInductionMotorEnv
from .squirrel_cage_induction_motor_envs import AbcContTorqueControlSquirrelCageInductionMotorEnv
from .squirrel_cage_induction_motor_envs import FiniteCurrentControlSquirrelCageInductionMotorEnv
from .squirrel_cage_induction_motor_envs import FiniteSpeedControlSquirrelCageInductionMotorEnv
from .squirrel_cage_induction_motor_envs import FiniteTorqueControlSquirrelCageInductionMotorEnv
