from .squirrel_cage_induction_motor_envs import ContCurrentControlSquirrelCageInductionMotorEnv
from .squirrel_cage_induction_motor_envs import ContSpeedControlSquirrelCageInductionMotorEnv
from .squirrel_cage_induction_motor_envs import ContTorqueControlSquirrelCageInductionMotorEnv
from .squirrel_cage_induction_motor_envs import FiniteCurrentControlSquirrelCageInductionMotorEnv
from .squirrel_cage_induction_motor_envs import FiniteSpeedControlSquirrelCageInductionMotorEnv
from .squirrel_cage_induction_motor_envs import FiniteTorqueControlSquirrelCageInductionMotorEnv

from .doubly_fed_induction_motor_envs import ContCurrentControlDoublyFedInductionMotorEnv
from .doubly_fed_induction_motor_envs import ContSpeedControlDoublyFedInductionMotorEnv
from .doubly_fed_induction_motor_envs import ContTorqueControlDoublyFedInductionMotorEnv
from .doubly_fed_induction_motor_envs import FiniteCurrentControlDoublyFedInductionMotorEnv
from .doubly_fed_induction_motor_envs import FiniteSpeedControlDoublyFedInductionMotorEnv
from .doubly_fed_induction_motor_envs import FiniteTorqueControlDoublyFedInductionMotorEnv
