# Version 1
from .gym_dcm.permex_dc_motor_env import ContSpeedControlDcPermanentlyExcitedMotorEnv
from .gym_dcm.permex_dc_motor_env import FiniteSpeedControlDcPermanentlyExcitedMotorEnv
from .gym_dcm.permex_dc_motor_env import ContTorqueControlDcPermanentlyExcitedMotorEnv
from .gym_dcm.permex_dc_motor_env import FiniteTorqueControlDcPermanentlyExcitedMotorEnv
from .gym_dcm.permex_dc_motor_env import ContCurrentControlDcPermanentlyExcitedMotorEnv
from .gym_dcm.permex_dc_motor_env import FiniteCurrentControlDcPermanentlyExcitedMotorEnv

from .gym_dcm.extex_dc_motor_env import ContSpeedControlDcExternallyExcitedMotorEnv
from .gym_dcm.extex_dc_motor_env import FiniteSpeedControlDcExternallyExcitedMotorEnv
from .gym_dcm.extex_dc_motor_env import ContTorqueControlDcExternallyExcitedMotorEnv
from .gym_dcm.extex_dc_motor_env import FiniteTorqueControlDcExternallyExcitedMotorEnv
from .gym_dcm.extex_dc_motor_env import ContCurrentControlDcExternallyExcitedMotorEnv
from .gym_dcm.extex_dc_motor_env import FiniteCurrentControlDcExternallyExcitedMotorEnv

from .gym_dcm.series_dc_motor_env import ContSpeedControlDcSeriesMotorEnv
from .gym_dcm.series_dc_motor_env import FiniteSpeedControlDcSeriesMotorEnv
from .gym_dcm.series_dc_motor_env import ContTorqueControlDcSeriesMotorEnv
from .gym_dcm.series_dc_motor_env import FiniteTorqueControlDcSeriesMotorEnv
from .gym_dcm.series_dc_motor_env import ContCurrentControlDcSeriesMotorEnv
from .gym_dcm.series_dc_motor_env import FiniteCurrentControlDcSeriesMotorEnv

from .gym_dcm.shunt_dc_motor_env import ContSpeedControlDcShuntMotorEnv
from .gym_dcm.shunt_dc_motor_env import FiniteSpeedControlDcShuntMotorEnv
from .gym_dcm.shunt_dc_motor_env import ContTorqueControlDcShuntMotorEnv
from .gym_dcm.shunt_dc_motor_env import FiniteTorqueControlDcShuntMotorEnv
from .gym_dcm.shunt_dc_motor_env import ContCurrentControlDcShuntMotorEnv
from .gym_dcm.shunt_dc_motor_env import FiniteCurrentControlDcShuntMotorEnv

from .gym_pmsm.finite_sc_pmsm_env import FiniteSpeedControlPermanentMagnetSynchronousMotorEnv
from .gym_pmsm.finite_cc_pmsm_env import FiniteCurrentControlPermanentMagnetSynchronousMotorEnv
from .gym_pmsm.finite_tc_pmsm_env import FiniteTorqueControlPermanentMagnetSynchronousMotorEnv
from .gym_pmsm.abccont_cc_pmsm_env import AbcContCurrentControlPermanentMagnetSynchronousMotorEnv
from .gym_pmsm.abccont_sc_pmsm_env import AbcContSpeedControlPermanentMagnetSynchronousMotorEnv
from .gym_pmsm.abccont_tc_pmsm_env import AbcContTorqueControlPermanentMagnetSynchronousMotorEnv
from .gym_pmsm.dqcont_sc_pmsm_env import DqContSpeedControlPermanentMagnetSynchronousMotorEnv
from .gym_pmsm.dqcont_tc_pmsm_env import DqContTorqueControlPermanentMagnetSynchronousMotorEnv
from .gym_pmsm.dqcont_cc_pmsm_env import DqContCurrentControlPermanentMagnetSynchronousMotorEnv

from .gym_synrm.finite_sc_synrm_env import FiniteSpeedControlSynchronousReluctanceMotorEnv
from .gym_synrm.finite_cc_synrm_env import FiniteCurrentControlSynchronousReluctanceMotorEnv
from .gym_synrm.finite_tc_synrm_env import FiniteTorqueControlSynchronousReluctanceMotorEnv
from .gym_synrm.abccont_tc_synrm_env import AbcContTorqueControlSynchronousReluctanceMotorEnv
from .gym_synrm.abccont_cc_synrm_env import AbcContCurrentControlSynchronousReluctanceMotorEnv
from .gym_synrm.abccont_sc_synrm_env import AbcContSpeedControlSynchronousReluctanceMotorEnv
from .gym_synrm.dqcont_cc_synrm_env import DqContCurrentControlSynchronousReluctanceMotorEnv
from .gym_synrm.dqcont_sc_synrm_env import DqContSpeedControlSynchronousReluctanceMotorEnv
from .gym_synrm.dqcont_tc_synrm_env import DqContTorqueControlSynchronousReluctanceMotorEnv

from .gym_im import DqContSpeedControlSquirrelCageInductionMotorEnv
from .gym_im import DqContCurrentControlSquirrelCageInductionMotorEnv
from .gym_im import DqContTorqueControlSquirrelCageInductionMotorEnv
from .gym_im import AbcContSpeedControlSquirrelCageInductionMotorEnv
from .gym_im import AbcContCurrentControlSquirrelCageInductionMotorEnv
from .gym_im import AbcContTorqueControlSquirrelCageInductionMotorEnv
from .gym_im import FiniteSpeedControlSquirrelCageInductionMotorEnv
from .gym_im import FiniteCurrentControlSquirrelCageInductionMotorEnv
from .gym_im import FiniteTorqueControlSquirrelCageInductionMotorEnv

from .gym_im import DqContSpeedControlDoublyFedInductionMotorEnv
from .gym_im import DqContCurrentControlDoublyFedInductionMotorEnv
from .gym_im import DqContTorqueControlDoublyFedInductionMotorEnv
from .gym_im import AbcContSpeedControlDoublyFedInductionMotorEnv
from .gym_im import AbcContCurrentControlDoublyFedInductionMotorEnv
from .gym_im import AbcContTorqueControlDoublyFedInductionMotorEnv
from .gym_im import FiniteSpeedControlDoublyFedInductionMotorEnv
from .gym_im import FiniteCurrentControlDoublyFedInductionMotorEnv
from .gym_im import FiniteTorqueControlDoublyFedInductionMotorEnv
