from .mechanical_load import MechanicalLoad
from .constant_speed_load import ConstantSpeedLoad
from .ornstein_uhlenbeck_load import OrnsteinUhlenbeckLoad
from .polynomial_static_load import PolynomialStaticLoad
from .external_speed_load import ExternalSpeedLoad
