from .cont_cc_permex_dc_env import ContCurrentControlDcPermanentlyExcitedMotorEnv
from .cont_tc_permex_dc_env import ContTorqueControlDcPermanentlyExcitedMotorEnv
from .cont_sc_permex_dc_env import ContSpeedControlDcPermanentlyExcitedMotorEnv
from .finite_tc_permex_dc_env import FiniteTorqueControlDcPermanentlyExcitedMotorEnv
from .finite_sc_permex_dc_env import FiniteSpeedControlDcPermanentlyExcitedMotorEnv
from .finite_cc_permex_dc_env import FiniteCurrentControlDcPermanentlyExcitedMotorEnv
