from .permex_dc_motor_env import ContSpeedControlDcPermanentlyExcitedMotorEnv
from .permex_dc_motor_env import FiniteSpeedControlDcPermanentlyExcitedMotorEnv
from .permex_dc_motor_env import ContTorqueControlDcPermanentlyExcitedMotorEnv
from .permex_dc_motor_env import FiniteTorqueControlDcPermanentlyExcitedMotorEnv
from .permex_dc_motor_env import ContCurrentControlDcPermanentlyExcitedMotorEnv
from .permex_dc_motor_env import FiniteCurrentControlDcPermanentlyExcitedMotorEnv

from .extex_dc_motor_env import ContSpeedControlDcExternallyExcitedMotorEnv
from .extex_dc_motor_env import FiniteSpeedControlDcExternallyExcitedMotorEnv
from .extex_dc_motor_env import ContTorqueControlDcExternallyExcitedMotorEnv
from .extex_dc_motor_env import FiniteTorqueControlDcExternallyExcitedMotorEnv
from .extex_dc_motor_env import ContCurrentControlDcExternallyExcitedMotorEnv
from .extex_dc_motor_env import FiniteCurrentControlDcExternallyExcitedMotorEnv

from .dc_series_motor_env import ContSpeedControlDcSeriesMotorEnv
from .dc_series_motor_env import FiniteSpeedControlDcSeriesMotorEnv
from .dc_series_motor_env import ContTorqueControlDcSeriesMotorEnv
from .dc_series_motor_env import FiniteTorqueControlDcSeriesMotorEnv
from .dc_series_motor_env import ContCurrentControlDcSeriesMotorEnv
from .dc_series_motor_env import FiniteCurrentControlDcSeriesMotorEnv

from .dc_shunt_motor_env import ContSpeedControlDcShuntMotorEnv
from .dc_shunt_motor_env import FiniteSpeedControlDcShuntMotorEnv
from .dc_shunt_motor_env import ContTorqueControlDcShuntMotorEnv
from .dc_shunt_motor_env import FiniteTorqueControlDcShuntMotorEnv
from .dc_shunt_motor_env import ContCurrentControlDcShuntMotorEnv
from .dc_shunt_motor_env import FiniteCurrentControlDcShuntMotorEnv
