# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys


os.environ.setdefault("MPLBACKEND", "Agg")
os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
try:
    import matplotlib; matplotlib.use("Agg")
except Exception:
    pass

autodoc_mock_imports = [
    "tkinter","tkinter.ttk","tkinter.filedialog",
    "IPython","IPython.display",
    # add more if needed in your project:
    "PyQt5","PyQt6","PySide2","PySide6","OpenGL","OpenGL.GL","cv2",
    "PIL.ImageTk","wx","gi","kivy","vispy","glfw",
]
sys.path.insert(0, os.path.abspath('..'))
# -- Project information -----------------------------------------------------

project = 'gym-electric-motor'
copyright = '2021, Praneeth Balakrishna, Gerrit Book, Felix Book, Darius Jakobeit, Wilhelm Kirchgässner, Maximilian Schenke, Arne Traue, Oliver Wallscheid'
author = 'Praneeth Balakrishna, Gerrit Book, Felix Book, Darius Jakobeit, Wilhelm Kirchgässner, Maximilian Schenke, Arne Traue, Oliver Wallscheid'

# The short X.Y version
version = ''
# The full version, including alpha/beta/rc tags
release = '2021'


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.mathjax',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'sphinx_rtd_theme',
    'myst_parser',
    'sphinx.ext.intersphinx'
]
html_theme = "sphinx_rtd_theme"
# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
#source_suffix = ['.rst', '.md']
# You can specify multiple suffix as a list of string:
# source_suffix = '.rst'
source_suffix = { ".rst": "restructuredtext", ".md": "myst" }

# MyST features
myst_enable_extensions = ["colon_fence", "deflist", "dollarmath", "amsmath"]
autosummary_generate = True
autodoc_default_options = {
    "members": True,
    "undoc-members": True,
    "inherited-members": True,
    "show-inheritance": True,
    "member-order": "groupwise",
}

# Cross-link to external docs
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", {}),
    "gem_control": ("https://upb-lea.github.io/gem-control/", None),
}
# The master toctree document.
master_doc = 'index'

# Include Constructor documentation
autoclass_content = 'both'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"
# Don't look for translation catalogs (avoids "locale_dir ... does not exist")
locale_dirs = []
# (optional) keeps .po files ungrouped if you ever add i18n later
gettext_compact = False
# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#


# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'GEM-doc'


# -- Options for LaTeX output ------------------------------------------------
latex_packages = r'''
\usepackage{amsmath}
'''

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    'preamble': r'''
\usepackage{amsmath}
''',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
    #'packages': latex_packages
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'gem-doc.tex', 'GEM Documentation',
     'Praneeth Balakrishna, Gerrit Book, Felix Book, Darius Jakobeit, Wilhelm Kirchgässner, Maximilian Schenke, Arne Traue, Oliver Wallscheid', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'gem', 'GEM Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'GEM', 'GEM Documentation',
     author, 'GEM', 'A package to simulate and control electrical drives.',
     'Miscellaneous'),
]
# -- Extension configuration -------------------------------------------------
