from .cont_cc_scim_env import ContCurrentControlSquirrelCageInductionMotorEnv
from .cont_sc_scim_env import ContSpeedControlSquirrelCageInductionMotorEnv
from .cont_tc_scim_env import ContTorqueControlSquirrelCageInductionMotorEnv
from .finite_cc_scim_env import FiniteCurrentControlSquirrelCageInductionMotorEnv
from .finite_sc_scim_env import FiniteSpeedControlSquirrelCageInductionMotorEnv
from .finite_tc_scim_env import FiniteTorqueControlSquirrelCageInductionMotorEnv
